import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { PortfolioData } from '../types.js';

const SAGE = rgb(124 / 255, 155 / 255, 138 / 255);
const INK = rgb(45 / 255, 59 / 255, 54 / 255);
const MUTED = rgb(120 / 255, 130 / 255, 125 / 255);
const WHITE = rgb(1, 1, 1);

export async function renderPortfolioPdf(
  data: PortfolioData,
  summary: string,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const { width, height } = page.getSize();
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const italic = await doc.embedFont(StandardFonts.HelveticaOblique);
  const displayName = `${data.firstName} ${data.lastName}`.trim();

  page.drawRectangle({ x: 0, y: height - 72, width, height: 72, color: SAGE });
  page.drawCircle({ x: 52, y: height - 36, size: 22, color: rgb(0.55, 0.72, 0.62) });
  page.drawText('PORTFOLIO', {
    x: 84,
    y: height - 44,
    size: 22,
    font: bold,
    color: WHITE,
  });

  let y = height - 110;
  page.drawText(displayName, { x: 48, y, size: 24, font: bold, color: INK });
  y -= 22;
  page.drawText(data.title, { x: 48, y, size: 14, font: regular, color: MUTED });

  const stats = [
    { num: String(data.projectCount), label: 'Projects' },
    { num: String(data.logCount), label: 'Logs' },
    { num: String(data.yearsActive), label: 'Years Active' },
  ];
  y -= 48;
  const boxW = (width - 96 - 24) / 3;
  stats.forEach((stat, i) => {
    const x = 48 + i * (boxW + 12);
    page.drawRectangle({
      x,
      y: y - 52,
      width: boxW,
      height: 56,
      borderColor: SAGE,
      borderWidth: 1.5,
    });
    page.drawText(stat.num, {
      x: x + 12,
      y: y - 22,
      size: 20,
      font: bold,
      color: INK,
    });
    page.drawText(stat.label, {
      x: x + 12,
      y: y - 40,
      size: 9,
      font: regular,
      color: MUTED,
    });
  });

  y -= 88;
  page.drawText('Professional Summary', { x: 48, y, size: 12, font: bold, color: INK });
  y -= 18;
  const summaryLines = wrapText(summary, 92);
  for (const line of summaryLines.slice(0, 8)) {
    page.drawText(line, { x: 48, y, size: 11, font: italic, color: INK });
    y -= 14;
  }

  if (data.skills?.length) {
    y -= 12;
    page.drawText('Skills', { x: 48, y, size: 12, font: bold, color: INK });
    y -= 20;
    let chipX = 48;
    for (const skill of data.skills.slice(0, 12)) {
      const chipW = regular.widthOfTextAtSize(skill, 9) + 16;
      if (chipX + chipW > width - 48) {
        chipX = 48;
        y -= 22;
      }
      page.drawRectangle({ x: chipX, y: y - 12, width: chipW, height: 18, color: SAGE });
      page.drawText(skill, { x: chipX + 8, y: y - 8, size: 9, font: regular, color: WHITE });
      chipX += chipW + 8;
    }
  }

  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  page.drawText(`Generated by Soren · JobSite Intel AI · ${dateStr}`, {
    x: 48,
    y: 36,
    size: 8,
    font: regular,
    color: MUTED,
  });

  return doc.save();
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (next.length > maxChars && line) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines;
}
