// AUTO-GENERATED by scripts/generate-jobsite-qa.ts — do not edit manually.

import type { SorenQAPair } from '../../types.js';

export const JOBSITE_QA: SorenQAPair[] = [
  {
    "q": "How do I create a daily log?",
    "a": "Tap New Log on the home screen, add photos, record a voice note, then tap Submit. Soren writes the report for you.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Can I add photos after submitting?",
    "a": "Not after submitting — add all photos before you tap Submit. You can create a new log entry if needed.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "What happens if my voice note is too short?",
    "a": "Soren will still generate a report from your photos and any typed notes. Even a 3-second note is fine.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "How do I start today's field report?",
    "a": "Open Soren or Home, tap Daily Log, pick your project, then add photos and a voice note before Submit.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Can I edit a log before submitting?",
    "a": "Yes — review everything on the capture screen and edit notes or retake photos before you submit.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "What project do I pick for a daily log?",
    "a": "Choose the active job from your project list. Soren remembers your last project for next time.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Do I need internet to create a log?",
    "a": "You can capture offline; submit when you are back online so Soren can generate the report.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "How many photos can I add per log?",
    "a": "Add as many site photos as you need before submitting — there is no low limit for field documentation.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Can I type instead of using voice?",
    "a": "Yes — type notes in the capture screen. Voice and typed notes both feed Soren's report.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "What time should I submit my daily log?",
    "a": "Submit before end of shift so weather and crew details stay accurate for the day.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Can foremen log for the whole crew?",
    "a": "Each log reflects what you document. Note crew count and trades in your voice note or notes.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "How do I log weather on site?",
    "a": "Weather is pulled automatically from your project address when you submit — you do not enter it manually.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Can I duplicate yesterday's log?",
    "a": "Start a new log for today; Soren uses fresh photos and notes rather than copying prior entries.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "What if I forget to log today?",
    "a": "Open Daily Log anytime and submit — backdating is not supported; log for the current work day.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "How do I add crew count to a log?",
    "a": "Say crew count in your voice note, e.g. \"12 guys on site plus 2 inspectors.\"",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Can I log multiple projects in one day?",
    "a": "Create a separate daily log per project so reports stay organized per job.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "What fields are required on a log?",
    "a": "At minimum: project, photos or notes, and Submit. Voice is optional but recommended.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "How long does report generation take?",
    "a": "Usually under a minute after submit. You will get a push when the PDF is ready.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Can I save a draft without submitting?",
    "a": "Stay on the capture screen until ready — submit when photos and notes are complete.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "Who sees my daily logs?",
    "a": "Your org team and anyone you share the report with. Clients only see what you send them.",
    "tags": [
      "daily-log"
    ]
  },
  {
    "q": "How do I download my PDF report?",
    "a": "After submitting a log, wait for Soren to finish, then tap Download Report on the result screen.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Can I send the report to my client?",
    "a": "Yes — tap Share on any report to send via email, text, or any app on your phone.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "What is the Build Book closeout?",
    "a": "The Build Book is a complete project closeout document with all logs, photos, and a project summary. Generate it when you close a job.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Where is my PDF stored?",
    "a": "Reports live in your project history. Download or share anytime from the log list.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Can I print a daily report?",
    "a": "Download the PDF, then open it and use Print from your device share sheet.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "How do I share a report by email?",
    "a": "Tap Share on the report, choose Mail, and pick your client's address.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "What format are reports exported in?",
    "a": "PDF — ready for email, print, and client records.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Can I regenerate a report?",
    "a": "Submit updates as a new log entry; each submission produces its own report.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "How do I find old reports?",
    "a": "Open the project, then Logs — browse by date.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Does the report include photos?",
    "a": "Yes — photos you attached appear in the generated PDF.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Can I brand reports with my company logo?",
    "a": "Org branding settings apply where configured in your account.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "What is in the executive summary?",
    "a": "Soren writes a concise summary of work, weather, crew, and issues from your capture.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "How do I export all logs for a project?",
    "a": "Use Build Book closeout for a full project package.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Can clients view reports without the app?",
    "a": "Yes — shared PDF links and attachments work outside the app.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Why is my report still processing?",
    "a": "Large photo sets can take longer. Wait for the ready notification.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "How do I rename a report?",
    "a": "Reports are titled by date and project — open the log detail to see the full title.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Can I combine multiple days into one PDF?",
    "a": "Build Book closeout aggregates project logs for closeout documentation.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "What if PDF download fails?",
    "a": "Check connection and retry. If it persists, contact support from Settings.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "Are reports searchable?",
    "a": "Search within a project's log list by date or keywords in titles.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "How do I archive completed project reports?",
    "a": "Mark the project complete and generate Build Book for your records.",
    "tags": [
      "reports"
    ]
  },
  {
    "q": "How do voice notes work?",
    "a": "Tap the mic on the capture screen, speak naturally, and stop when done. Soren transcribes and uses it in your report.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Can I speak in Spanish?",
    "a": "Yes — record in Spanish and Soren can produce bilingual English and Spanish report content.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "What if the mic does not work?",
    "a": "Check app microphone permission in iOS/Android settings, then retry.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "How long can a voice note be?",
    "a": "There is no strict short limit — keep it concise for faster processing.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Can I re-record a voice note?",
    "a": "Yes — delete or replace the clip before submitting the log.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Does Soren transcribe automatically?",
    "a": "Yes — transcription runs as part of report generation after submit.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Can I edit the transcript?",
    "a": "Edit typed notes on the capture screen to correct anything before submit.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Is voice required for every log?",
    "a": "No — photos plus typed notes are enough if you prefer not to use voice.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "How noisy can the job site be?",
    "a": "Speak clearly near the phone; extreme noise may reduce transcript quality.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Can I use voice on Android?",
    "a": "Yes — voice capture works on iOS and Android in the Capacitor app.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "What language does Soren expect?",
    "a": "English and Spanish are supported for field voice notes.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Why was my voice note empty?",
    "a": "Ensure mic permission is granted and you tapped stop after speaking.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Can inspectors hear my voice notes?",
    "a": "Voice feeds the written report — clients typically receive the PDF, not raw audio.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "How do I test my microphone?",
    "a": "Record a short test on the capture screen before your real log.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Does voice work offline?",
    "a": "You can record offline; upload and transcription happen when you submit online.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Can I pause while recording?",
    "a": "Use stop and re-record if needed — one continuous clip per capture is simplest.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Will Soren quote me verbatim?",
    "a": "Soren summarizes professionally — not always word-for-word from audio.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Can I add voice after photos?",
    "a": "Yes — order does not matter before submit.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "Is voice data stored securely?",
    "a": "Audio is processed for your report under your org's data policies.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "How do I disable voice prompts?",
    "a": "Simply skip the mic and use typed notes instead.",
    "tags": [
      "voice"
    ]
  },
  {
    "q": "How do I add photos to a log?",
    "a": "Tap Add Photos on the capture screen and pick from camera or gallery.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Can I add video?",
    "a": "Video support depends on your app version — check the capture screen for Add Video.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "What photo quality is best?",
    "a": "Use clear, well-lit shots of work in progress — no need for pro camera settings.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "How many photos per log?",
    "a": "Add as many as needed to document the day's work.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Can I delete a photo before submit?",
    "a": "Yes — remove unwanted shots on the capture screen.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Do photos upload on cellular?",
    "a": "Yes — photos upload when you submit if you are on mobile data.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Why are photos blurry in the PDF?",
    "a": "Use original camera resolution; avoid heavy compression in gallery picks.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Can I annotate photos?",
    "a": "Markup depends on host app features — document details in voice or notes too.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Are GPS tags used?",
    "a": "Project address drives weather — photo GPS may be used where enabled.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Can I reorder photos?",
    "a": "Reorder if the capture UI supports it; otherwise order in PDF follows upload order.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "What if upload stalls?",
    "a": "Check signal and retry submit. Large batches need stable connection.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Can I photograph documents?",
    "a": "Yes — include delivery tickets, permits, or signs as needed.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Do clients see all photos?",
    "a": "Clients see photos included in reports you share.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "How do I capture progress photos daily?",
    "a": "Make photos part of your daily log habit before submit.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Can I use iPad camera?",
    "a": "Yes — JobSite Intel works on phones and tablets.",
    "tags": [
      "photos"
    ]
  },
  {
    "q": "Where does the weather come from?",
    "a": "Weather is automatically pulled from Open-Meteo based on your project address when you submit a log.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "Can I override weather?",
    "a": "Weather is auto-filled from the project location — edit notes if conditions differ on site.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "Why is weather wrong?",
    "a": "Verify the project address is correct in project settings.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "Does weather show rain amounts?",
    "a": "Reports include precip and conditions from Open-Meteo for the log date.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "Is weather in the PDF?",
    "a": "Yes — daily weather appears in the generated report.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "What if my site has no address yet?",
    "a": "Set a valid project address so weather can resolve.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "Does weather update hourly?",
    "a": "Snapshot is taken for your submission time and date.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "Can I see weather on the capture screen?",
    "a": "Weather preview may show on supported screens before submit.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "Is wind speed included?",
    "a": "Extended weather fields include wind and humidity where available.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "What weather source is used?",
    "a": "Open-Meteo — free global weather data for job sites.",
    "tags": [
      "weather"
    ]
  },
  {
    "q": "How do I create a project?",
    "a": "Go to Projects → New Project and enter the job name and address.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "How do I switch projects?",
    "a": "Pick the project from Home or the log capture flow.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "Can I close a completed job?",
    "a": "Use Build Book closeout when the job is finished.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "How many projects can I have?",
    "a": "Limits depend on your plan — free tier allows active projects per org policy.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "Who can see all projects?",
    "a": "Org members see projects their role permits.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "How do I edit a project address?",
    "a": "Open project settings and update the site address for weather and reports.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "Can I archive a project?",
    "a": "Mark complete and generate closeout documentation.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "What is an active project?",
    "a": "A job currently receiving daily logs.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "How do I invite someone to one project?",
    "a": "Team access is org-wide — manage members in Settings → Team.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "Can I duplicate a project?",
    "a": "Create a new project entry for a new job site.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "How do I name projects?",
    "a": "Use client and site name, e.g. \"Santana Heights\".",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "What is project closeout?",
    "a": "Final documentation package via Build Book.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "Can I delete a project?",
    "a": "Owners can remove projects per org policy — check Settings.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "How do logs tie to projects?",
    "a": "Every log belongs to one project for organized history.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "Can I filter logs by project?",
    "a": "Open a project to see only its logs.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "How do I set a default project?",
    "a": "Soren remembers your last used project for quick logging.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "What if I pick wrong project?",
    "a": "Do not submit — switch project before submit, or create a correcting log.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "Are subcontractors per-project?",
    "a": "Document subs in daily log notes.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "How do I track multiple sites?",
    "a": "One project per site is recommended.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "Can PMs see all sites?",
    "a": "PM and superintendent roles see org projects per permissions.",
    "tags": [
      "projects"
    ]
  },
  {
    "q": "What is Build Book?",
    "a": "A complete closeout PDF with all logs, photos, and summary for handoff.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "When should I generate Build Book?",
    "a": "When the job is substantially complete or at client handoff.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "How do I start closeout?",
    "a": "Open the project → Closeout or Build Book from the project menu.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Does Build Book include weather history?",
    "a": "Yes — aggregated from daily logs across the project.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Can I share Build Book with the owner?",
    "a": "Download or share the closeout PDF like any report.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "How long does closeout take?",
    "a": "Depends on log count — large projects may take a few minutes.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Is Build Book different from daily PDF?",
    "a": "Yes — it is a full project archive, not a single day.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Can I regenerate Build Book?",
    "a": "Run closeout again if you add late logs — check for updated export.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "What if closeout fails?",
    "a": "Ensure all logs are synced and retry. Contact support if needed.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Does closeout need owner approval?",
    "a": "That is your workflow — the PDF is yours to deliver.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Are change orders in Build Book?",
    "a": "Include change order notes in daily logs so they appear in history.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Can I customize closeout cover?",
    "a": "Template follows construction-superintendent format in v1.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Who can run closeout?",
    "a": "Users with project admin permissions.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "Is Build Book required?",
    "a": "Optional but recommended for professional handoff.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "What files are in closeout?",
    "a": "Typically one consolidated PDF plus summaries.",
    "tags": [
      "build-book"
    ]
  },
  {
    "q": "How do push notifications work?",
    "a": "Enable notifications in device settings to get report-ready and reminder alerts.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "How do I enable push?",
    "a": "Allow notifications when prompted in the app.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "What is report-ready push?",
    "a": "You get notified when your PDF finishes generating.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "Can I turn off announcements?",
    "a": "Settings → Product announcements toggle controls marketing pushes.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "Do reminders use push or local?",
    "a": "Daily log reminders may use local notifications on device.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "Why am I not getting pushes?",
    "a": "Check OS notification permission and in-app settings.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "Can clients get pushes?",
    "a": "Clients receive reports you send — not app pushes unless they use the app.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "How do I notify a client from Soren?",
    "a": "Use Notify Client action or share a report from the log.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "Are pushes free?",
    "a": "Yes — notifications are part of the app.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "How do I unregister a device?",
    "a": "Log out or disable notifications in Settings.",
    "tags": [
      "notifications"
    ]
  },
  {
    "q": "How do I add team members?",
    "a": "Go to Settings → Team to invite crew members by email.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "How do I change my password?",
    "a": "Settings → Account → change password or use forgot password on sign-in.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "Can I use this in Spanish?",
    "a": "Yes — record your voice note in Spanish and Soren will generate a bilingual report.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "How do I update my profile?",
    "a": "Settings → Profile for name and contact info.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "Can I have multiple orgs?",
    "a": "Switch org from Settings if you belong to more than one.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "How do I delete my account?",
    "a": "Contact support or use account deletion in Settings where available.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "Who is the org owner?",
    "a": "The owner manages billing and team in Settings.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "How do roles work?",
    "a": "Admin, member, and owner roles control team and project access.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "Can I change my email?",
    "a": "Update email in Settings → Account with verification.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "How do I sign out?",
    "a": "Settings → Sign out.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "Is two-factor available?",
    "a": "Check Settings → Security for MFA if enabled for your org.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "How do I contact support?",
    "a": "Settings → Help or support email in the app store listing.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "Can I export my data?",
    "a": "Request export from support for GDPR-style requests.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "How do I update the app?",
    "a": "Install updates from the App Store or Play Store.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "What devices are supported?",
    "a": "iOS and Android via the JobSite Intel app.",
    "tags": [
      "account"
    ]
  },
  {
    "q": "How much does JobSite Intel cost?",
    "a": "JobSite Intel AI is free during the current period. Paid plans are coming soon.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "Is there a free trial?",
    "a": "The app is free to use during the current promotional period.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "Will pricing change?",
    "a": "We will announce paid plans before charges apply.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "Do I need a credit card?",
    "a": "Not during the free period for standard signup.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "Is billing per user or per org?",
    "a": "Future plans will be announced on the pricing page.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "Can I cancel anytime?",
    "a": "During free period there is nothing to cancel.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "Are there enterprise plans?",
    "a": "Contact sales for multi-org enterprise needs.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "Do clients pay?",
    "a": "Billing is for contractors using the app, not homeowners.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "What happens when free period ends?",
    "a": "You will receive notice and upgrade options before any charge.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "Where is the pricing page?",
    "a": "Check jobsiteintel.com or in-app Settings → Billing when live.",
    "tags": [
      "billing"
    ]
  },
  {
    "q": "What's the weather today?",
    "a": "I only know construction — for today's forecast, check your weather app. I'll pull weather for your job site when you log.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Who won the game last night?",
    "a": "That's outside what I know today. We're always adding more.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Write me a poem.",
    "a": "I focus on construction field work — try Daily Log or Ask Soren about JobSite Intel.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "What is the stock market doing?",
    "a": "I only help with JobSite Intel — logs, reports, and projects.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Order me lunch.",
    "a": "I can't do that — but I can help you document today's site work.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "What is the meaning of life?",
    "a": "On the job site: document, communicate, and close out strong. Ask me about daily logs!",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Tell me a joke.",
    "a": "I'm better at daily reports than comedy — ask about voice notes or PDFs.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "How do I fix my truck?",
    "a": "That's outside what I know today. We're always adding more.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "What movie should I watch?",
    "a": "I only know construction — try Ask Soren about portfolio or reports.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Book me a flight.",
    "a": "I help with JobSite Intel only — projects, logs, and client updates.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "What is quantum physics?",
    "a": "Outside my scope — ask about Build Book or team settings instead.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Play music.",
    "a": "I'm your field assistant for documentation, not a music player.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "What is two plus two?",
    "a": "That's outside what I know today. We're always adding more.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Who is the president?",
    "a": "I focus on JobSite Intel features — try a product question.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Translate this to French.",
    "a": "I support English and Spanish for reports — not general translation.",
    "tags": [
      "out-of-scope"
    ]
  },
  {
    "q": "Can I log in Spanish?",
    "a": "Yes — record voice in Spanish; Soren can produce bilingual reports.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "Does the app UI speak Spanish?",
    "a": "UI language depends on device settings; reports can be bilingual.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "How do bilingual reports work?",
    "a": "Soren generates English and Spanish content from your Spanish voice note.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "Can clients read Spanish reports?",
    "a": "Share the bilingual PDF — both languages can be included.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "Do I type in Spanish?",
    "a": "Yes — typed Spanish notes work like voice.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "Is Spanish transcription accurate?",
    "a": "Speak clearly; quality matches general Spanish field speech.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "Can supers only use English?",
    "a": "Use whichever language fits your crew — both are supported.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "Are templates in Spanish?",
    "a": "Report narrative can include Spanish per bilingual setting.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "How do I switch report language?",
    "a": "Record in Spanish for bilingual output; settings may expand later.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "Is support available in Spanish?",
    "a": "Contact support — we help all JobSite Intel users.",
    "tags": [
      "spanish"
    ]
  },
  {
    "q": "Who is Soren?",
    "a": "Soren is your AI field assistant inside JobSite Intel — logs, reports, and answers.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "What can Soren do?",
    "a": "Help you log work, generate reports, build portfolio, and answer JobSite questions.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Is Soren a real person?",
    "a": "Soren is AI built by Varshyl to help supers and foremen in the field.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Does Soren use ChatGPT?",
    "a": "Soren uses Varshyl's AI stack — optimized for construction daily reports.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "How smart is Soren?",
    "a": "Soren is trained for JobSite workflows — not general trivia.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Can Soren schedule my crew?",
    "a": "Not yet — use daily logs and team settings for crew documentation.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Does Soren replace a PM?",
    "a": "No — Soren assists documentation; you stay in charge of the job.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "How do I ask Soren questions?",
    "a": "Tap Ask Soren or type in the input bar on the Soren screen.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Will Soren learn my projects?",
    "a": "Soren uses your org's logs and settings — not open internet search.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Is my data used to train AI?",
    "a": "See privacy policy — your org controls data handling.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Can Soren email my client?",
    "a": "Use Notify Client or Share report — Soren drafts from your logs.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "What is Soren's avatar?",
    "a": "The construction assistant emoji on the Soren screen.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "How do I reset Soren identity?",
    "a": "Clear Soren session in app storage or re-enter name on first open.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Does Soren work on web?",
    "a": "Yes — Soren screen works in browser and Capacitor app.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Can I turn off Soren?",
    "a": "Use Home and logs without opening Soren — it is optional help.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Does Soren support voice on Soren screen?",
    "a": "Tap the mic on the input row to ask by voice where enabled.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "How often is Soren updated?",
    "a": "Q&A and skills expand with each app release.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Can Soren build my resume?",
    "a": "Yes — tap My Portfolio for PDF and share options.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "What is portfolio builder?",
    "a": "Soren summarizes your logs into a superintendent portfolio.",
    "tags": [
      "soren-ai"
    ]
  },
  {
    "q": "Is Soren available offline?",
    "a": "Some features need network — capture can work offline before submit.",
    "tags": [
      "soren-ai"
    ]
  }
] as SorenQAPair[];
