import type { CSSProperties } from 'react';

export const grantsAdminStyles = {
  root: {
    background: 'var(--mp-surface, #1a1a1a)',
    color: 'var(--mp-ink, #e5e5e5)',
    fontFamily: 'var(--mp-font-body, Inter, system-ui, sans-serif)',
    padding: 24,
    borderRadius: 'var(--mp-radius, 8px)',
  } satisfies CSSProperties,
  section: { marginBottom: 28 } satisfies CSSProperties,
  heading: {
    fontSize: '1.1rem',
    fontWeight: 600,
    margin: '0 0 12px',
    color: 'var(--mp-primary, #6366f1)',
  } satisfies CSSProperties,
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '0.9rem',
  } satisfies CSSProperties,
  th: {
    textAlign: 'left',
    padding: '8px 10px',
    borderBottom: '1px solid rgba(255,255,255,0.12)',
    fontWeight: 600,
  } satisfies CSSProperties,
  td: {
    padding: '8px 10px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  } satisfies CSSProperties,
  rowAlt: { background: 'rgba(255,255,255,0.03)' } satisfies CSSProperties,
  mono: { fontFamily: 'ui-monospace, monospace', textTransform: 'uppercase' as const },
  dangerBtn: {
    background: 'var(--mp-danger, #ef4444)',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    padding: '4px 10px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  } satisfies CSSProperties,
  field: { display: 'flex', flexDirection: 'column' as const, gap: 4, marginBottom: 10 },
  label: { fontSize: '0.85rem', opacity: 0.85 },
  input: {
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: 6,
    padding: '8px 10px',
    color: 'inherit',
  } satisfies CSSProperties,
  primaryBtn: {
    background: 'var(--mp-primary, #6366f1)',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    padding: '8px 14px',
    cursor: 'pointer',
    fontWeight: 600,
  } satisfies CSSProperties,
  success: { color: 'var(--mp-success, #10b981)', marginTop: 8 } satisfies CSSProperties,
  empty: { opacity: 0.7, fontStyle: 'italic' as const, margin: 0 },
  error: { color: 'var(--mp-danger, #ef4444)', marginBottom: 12 },
  toggleRow: { display: 'flex', gap: 8, marginBottom: 10 },
  toggleBtn: (active: boolean): CSSProperties => ({
    background: active ? 'var(--mp-primary, #6366f1)' : 'rgba(255,255,255,0.08)',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    padding: '6px 12px',
    cursor: 'pointer',
  }),
};
