import { Router } from 'express';
import { generateFixPackage } from './fix-generator.js';
import type { Platform } from './platform-detector.js';

const router: Router = Router();

router.options('/', (_req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.status(204).end();
});

router.post('/', (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');

  const { platform, failingChecks, siteInfo } = req.body as {
    platform: Platform;
    failingChecks: { name: string; tip: string }[];
    siteInfo: {
      url: string;
      productName?: string;
      companyName?: string;
    };
  };

  if (!platform || !failingChecks || !siteInfo?.url) {
    res.status(400).json({
      error: 'platform, failingChecks, and siteInfo.url required',
    });
    return;
  }

  try {
    const fixPackage = generateFixPackage(
      platform,
      failingChecks,
      siteInfo,
    );
    res.json(fixPackage);
  } catch (err) {
    console.error('Fix generator error:', err);
    res.status(500).json({ error: 'Fix generation failed' });
  }
});

router.options('/ai-package', (_req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.status(204).end();
});

router.post('/ai-package', (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');

  const { platform, failingChecks, siteInfo } = req.body as {
    platform: Platform;
    failingChecks: { name: string; tip: string }[];
    siteInfo: {
      url: string;
      productName?: string;
      companyName?: string;
    };
  };

  if (!platform || !failingChecks || !siteInfo?.url) {
    res.status(400).json({
      error: 'platform, failingChecks, siteInfo required',
    });
    return;
  }

  try {
    const pkg = generateFixPackage(platform, failingChecks, siteInfo);

    const fixCode = pkg.files
      .map((f) => `\n--- ${f.filename} ---\n${f.content}`)
      .join('\n');

    const steps = pkg.instructions
      .map((s) => `${s.step}. ${s.title}: ${s.detail}`)
      .join('\n');

    const aiPromptText = `
SOREN AI DISCOVERABILITY FIX PACKAGE
Site: ${siteInfo.url}
Platform: ${platform}
Generated by Soren Fixes It (soren.varshyl.com)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PASTE THIS INTO CHATGPT OR CLAUDE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I need help fixing my website's AI discoverability.
My site is ${siteInfo.url} and it runs on ${platform}.

Here are the exact issues and fix files:

Failing signals:
${failingChecks.map((c) => `- ${c.name}: ${c.tip}`).join('\n')}

Fix code:
${fixCode}

Steps to apply:
${steps}

Please help me apply these fixes step by step.
Start with the first file and guide me through it.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHAT'S IN THIS PACKAGE:
${pkg.files.map((f) => `- ${f.filename}: ${f.description}`).join('\n')}

HOW TO USE:
1. Open ChatGPT (chat.openai.com) or Claude (claude.ai)
2. Copy everything between the dashed lines above
3. Paste it into a new conversation
4. Your AI assistant will guide you through applying each fix
5. After applying, return to Soren and re-run the audit

Questions? Contact us at contact@jobsiteintelai.com
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Soren Fixes It · Built by Varshyl Inc · Pleasanton CA
`.trim();

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="soren-fix-${platform}.txt"`,
    );
    res.send(aiPromptText);
  } catch (err) {
    console.error('AI package error:', err);
    res.status(500).json({ error: 'AI package generation failed' });
  }
});

export default router;
