// AUTO-GENERATED by scripts/inline-client-css.ts — do not edit manually.

export const AUTH_SOCIAL_CLIENT_STYLES = `.as-social-buttons {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.as-social-button {
  display: flex;
  width: 100%;
  min-height: 44px;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 10px 16px;
  font-size: 14px;
  cursor: pointer;
  box-sizing: border-box;
}

.as-social-button:disabled {
  cursor: not-allowed;
  opacity: 0.6;
}

.as-social-button--official-apple {
  background: #000000;
  color: #ffffff;
  border: none;
  border-radius: 8px;
  font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', system-ui, sans-serif;
  font-weight: 600;
}

.as-social-button--official-google {
  background: #ffffff;
  color: #1f1f1f;
  border: 1px solid #dadce0;
  border-radius: 8px;
  font-family: Roboto, Arial, sans-serif;
  font-weight: 500;
}

.as-social-button--official-google:hover:not(:disabled) {
  background: #f8f9fa;
}

.as-logo {
  width: 20px;
  height: 20px;
  flex-shrink: 0;
}

.as-logo-apple {
  margin-right: 2px;
}

.auth-divider {
  display: flex;
  align-items: center;
  gap: 12px;
  margin: 16px 0;
}

.auth-divider-line {
  flex: 1;
  height: 1px;
  background: var(--as-divider-line, #e5e7eb);
}

.auth-divider-text {
  font-size: 14px;
  color: var(--as-divider-text, #6b7280);
  white-space: nowrap;
}
`;
