import type { SorenConfig, SorenPortfolioData, SorenSession } from '../types.js';

export interface SorenPortfolioProps {
  config: SorenConfig;
  session: SorenSession | null;
  data: SorenPortfolioData | null;
  onDownloadPdf: () => void;
  pdfLoading?: boolean;
}

const SHARE_LABELS: Record<string, { label: string; dotClass: string; icon: string }> = {
  linkedin: { label: 'LinkedIn', dotClass: 'soren-li-dot', icon: 'in' },
  tiktok: { label: 'TikTok', dotClass: 'soren-tt-dot', icon: '♪' },
  instagram: { label: 'Instagram', dotClass: 'soren-ig-dot', icon: '📷' },
};

export function SorenPortfolio({
  config,
  session,
  data,
  onDownloadPdf,
  pdfLoading = false,
}: SorenPortfolioProps) {
  const displayName = session?.name ?? 'Your Name';
  const title = session?.title ?? 'Professional';
  const stats = data ?? { projects: 0, logCount: 0, yearsActive: 0, skills: [] };
  const targets = config.portfolio?.shareTargets ?? ['linkedin', 'tiktok', 'instagram'];

  return (
    <div data-testid="soren-portfolio">
      <div className="soren-portfolio-card">
        <div className="soren-portfolio-top">
          <div className="soren-portfolio-avatar">{config.avatarEmoji}</div>
          <div className="soren-portfolio-info">
            <h3>{displayName}</h3>
            <p>{title} · {stats.yearsActive} years experience</p>
          </div>
        </div>
        <div className="soren-portfolio-stats">
          <div className="soren-stat">
            <div className="soren-stat-num">{stats.projects}</div>
            <div className="soren-stat-label">Projects</div>
          </div>
          <div className="soren-stat">
            <div className="soren-stat-num">{stats.logCount}</div>
            <div className="soren-stat-label">Daily Logs</div>
          </div>
          <div className="soren-stat">
            <div className="soren-stat-num">{stats.yearsActive}</div>
            <div className="soren-stat-label">Years</div>
          </div>
        </div>
        <div className="soren-portfolio-btns">
          <button type="button" className="soren-pbtn primary" onClick={onDownloadPdf} disabled={pdfLoading}>
            📄 {pdfLoading ? 'Generating…' : 'Download PDF'}
          </button>
          <button type="button" className="soren-pbtn secondary">🔗 Share Link</button>
        </div>
      </div>

      <div className="soren-sec-label">Share your profile</div>
      <div className="soren-share-row">
        {targets.map((target) => {
          const meta = SHARE_LABELS[target] ?? { label: target, dotClass: 'soren-li-dot', icon: '•' };
          return (
            <button key={target} type="button" className="soren-share-btn">
              <span className={`soren-share-dot ${meta.dotClass}`}>{meta.icon}</span>
              {meta.label}
            </button>
          );
        })}
      </div>

      <div className="soren-sec-label">Your Highlight Reel</div>
      <div className="soren-video-card">
        <div className="soren-video-thumb">
          <div className="soren-play-btn">▶</div>
        </div>
        <div className="soren-video-info">
          <h4>{displayName} · Career Highlights</h4>
          <p>{stats.projects} projects · {stats.logCount} daily logs · Auto-generated by Soren</p>
        </div>
      </div>
    </div>
  );
}
