/**
 * Inlines client component CSS into a generated TS module so ESM consumers
 * (and packed-tarball Node import tests) never side-effect-import .css files.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const componentsDir = join(scriptDir, '../src/client/components');
const outFile = join(scriptDir, '../src/client/clientStyles.generated.ts');

function escapeTemplateLiteral(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const socialButtons = readFileSync(join(componentsDir, 'SocialButtons.css'), 'utf8');
const authDivider = readFileSync(join(componentsDir, 'AuthDivider.css'), 'utf8');
const combined = `${socialButtons}\n${authDivider}`;

const body = `// AUTO-GENERATED by scripts/inline-client-css.ts — do not edit manually.

export const AUTH_SOCIAL_CLIENT_STYLES = \`${escapeTemplateLiteral(combined)}\`;
`;

writeFileSync(outFile, body, 'utf8');
console.log(`[auth-social] inlined client CSS → ${outFile}`);
