/**
 * Inlines client component CSS into a generated TS module so ESM consumers
 * (and packed-tarball Node import tests) never side-effect-import .css files.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const componentsDir = join(scriptDir, '../src/client/components');
const outFile = join(componentsDir, 'paywallStyles.generated.ts');

function escapeTemplateLiteral(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const paywallStyles = readFileSync(join(componentsDir, 'PaywallStyles.css'), 'utf8');

const body = `// AUTO-GENERATED by scripts/inline-mobile-payments-css.ts — do not edit manually.

export const PAYWALL_CSS = \`${escapeTemplateLiteral(paywallStyles)}\`;
`;

writeFileSync(outFile, body, 'utf8');
console.log(`[mobile-payments] inlined PaywallStyles.css → ${outFile}`);
