/**
 * Reads src/server/migrations/*.sql and emits migrations.generated.ts with
 * inlined SQL strings so bundled consumers never read the filesystem at runtime.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(scriptDir, '../src/server/migrations');
const outFile = join(scriptDir, '../src/server/migrations.generated.ts');

function escapeTemplateLiteral(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const files = readdirSync(migrationsDir)
  .filter((name) => name.endsWith('.sql'))
  .sort();

const entries = files.map((file) => {
  const sql = readFileSync(join(migrationsDir, file), 'utf8');
  const name = file.replace(/\.sql$/, '');
  return { name, sql };
});

const body = `// AUTO-GENERATED by scripts/inline-migrations.ts — do not edit manually.
// Regenerated on every build via the prebuild script.

export interface TmMigrationEntry {
  readonly name: string;
  readonly sql: string;
}

export const TM_MIGRATIONS: readonly TmMigrationEntry[] = [
${entries
  .map(
    (entry) => `  {
    name: ${JSON.stringify(entry.name)},
    sql: \`${escapeTemplateLiteral(entry.sql)}\`,
  },`,
  )
  .join('\n')}
] as const;
`;

writeFileSync(outFile, body, 'utf8');
console.log(`[tm] inlined ${entries.length} migration(s) → ${outFile}`);
