import type { FixFile, GeoAudit, SiteMetadata } from './types.js';
import { domainFromUrl } from './site-metadata.js';

export function buildPrompt(
  audit: GeoAudit,
  meta: SiteMetadata,
  files: FixFile[],
): string {
  const domain = domainFromUrl(meta.url);
  const failing = audit.checks.filter((c) => !c.passed);

  const fileBlocks = files
    .map(
      (f) => `### ${f.filename} (fixes: ${f.check})
\`\`\`
${f.content.trim()}
\`\`\``,
    )
    .join('\n\n');

  const checkList = failing
    .map((c) => `- ${c.name}: ${c.tip}`)
    .join('\n');

  return `SOREN GEO REPAIR PROMPT — ${domain}
Generated by Soren Fixes It. Paste this ENTIRE file into ChatGPT or Claude.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You are helping me apply AI discoverability fixes to my website.
Site: ${meta.url}
Platform: ${audit.platform}
Current score: ${audit.score}

FIRST — ask me ONE question before any changes:
"How is your website hosted?"
Choices: Static HTML, WordPress, Shopify, Wix, Squarespace, Webflow, Next.js, Other

Wait for my answer, then guide me through ONLY the failing checks below.
Do not suggest changes for checks that are not listed.

FAILING CHECKS ONLY:
${checkList}

FILES TO APPLY (one at a time — wait for my confirmation after each step):

${fileBlocks}

WORKFLOW RULES:
1. Confirm my hosting platform.
2. Walk through each file above in order.
3. After each file, wait until I confirm it is applied before continuing.
4. Never suggest edits beyond the failing checks listed.
5. End by telling me to re-run the free Soren GEO scan to verify the new score.

When all files are applied, congratulate me and remind me to rescan at soren.varshyl.com.
`;
}
