import type { FixFile, GeoAudit, SiteMetadata } from './types.js';
import { domainFromUrl } from './site-metadata.js';
import {
  isAdaOrSecurityCheck,
  PROMPT_ADA_SECURITY_INTRO,
} from './compliance-disclaimers.js';
import { scannerUrl } from './scanner-url.js';

function codeFenceFor(content: string): string {
  let longest = 0;
  for (const match of content.matchAll(/`{3,}/g)) {
    const len = match[0]?.length ?? 0;
    if (len > longest) longest = len;
  }
  return '`'.repeat(Math.max(3, longest + 1));
}

export function buildPrompt(
  audit: GeoAudit,
  meta: SiteMetadata,
  files: FixFile[],
): string {
  const domain = domainFromUrl(meta.url);
  const failing = audit.checks.filter((c) => !c.passed && !c.info);
  const hasAdaOrSecurity =
    failing.some((c) => isAdaOrSecurityCheck(c.name, c.category))
    || files.some((f) => isAdaOrSecurityCheck(f.check));

  const fileBlocks = files
    .map(
      (f) => {
        const body = f.content.trimEnd();
        const fence = codeFenceFor(body);
        return `### ${f.filename} (fixes: ${f.check})
${fence}
${body}
${fence}`;
      },
    )
    .join('\n\n');

  const checkList = failing
    .map((c) => `- ${c.name}: ${c.tip}`)
    .join('\n');

  const complianceBlock = hasAdaOrSecurity
    ? `
ACCESSIBILITY / SECURITY NOTICE (required before those fixes):
${PROMPT_ADA_SECURITY_INTRO}
`
    : '';

  return `SOREN GEO REPAIR PROMPT — ${domain}
Generated by Soren Fixes It. Paste this ENTIRE file into ChatGPT or Claude.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You are helping me apply AI discoverability fixes to my website.
Site: ${meta.url}
Platform: ${audit.platform}
Current score: ${audit.score}

FIRST — ask me ONE question before any changes:
"How is your website hosted?"
Choices: Static HTML, WordPress, Shopify, Wix, Squarespace, Webflow, Next.js, Other

Wait for my answer, then guide me through ONLY the failing checks below.
Do not suggest changes for checks that are not listed.
${complianceBlock}
FAILING CHECKS ONLY:
${checkList}

FILES TO APPLY (one at a time — wait for my confirmation after each step):

${fileBlocks}

WORKFLOW RULES:
1. Confirm my hosting platform.
2. If accessibility or security fixes are included, deliver the notice above and wait for confirmation before those files.
3. Walk through each file above in order.
4. After each file, wait until I confirm it is applied before continuing.
5. Never suggest edits beyond the failing checks listed.
6. End by telling me to re-run the free Soren GEO scan to verify the new score.

HOW TO APPLY THIS:
1. Ask me plainly: "How do you usually update your website?"
   - Site-builder login (WordPress, Wix, Squarespace, Shopify, Webflow)
   - Code on GitHub/GitLab
   - Hosting login only (Bluehost, GoDaddy, cPanel, Netlify)
   - A developer/agency manages it
   - Not sure
2. Route based on my answer:
   - GitHub/GitLab repo: offer to apply these exact changes directly by editing files and opening a PR.
   - WordPress: use Appearance → Theme File Editor and paste head snippets into header.php before </head>; or use an insert-headers plugin for the same snippets.
   - Wix: Settings → Custom code → Head, paste head snippets; use site settings/file tools for robots.txt and sitemap.xml updates.
   - Squarespace: Settings → Advanced → Code Injection → Header for head snippets; use site settings for robots.txt and sitemap.xml.
   - Shopify: Online Store → Themes → Edit code → layout/theme.liquid, paste snippets before </head>; update robots.txt.liquid and structured data files in theme code.
   - Webflow: Project Settings → Custom Code → Head Code for snippets; use hosting/export workflow to update robots.txt, sitemap.xml, and JSON-LD.
   - cPanel/hosting login: File Manager → open the site root/public_html and edit the relevant files directly.
   - Developer/agency-managed: provide a short forwardable note:
     "Please apply the attached GEO fixes exactly as listed, one file at a time, then confirm when done so we can rescan at varshylai.com/scan/."
   - Not sure/other: use this fallback:
     "Tell me your platform and I'll adapt these standard <head>, robots.txt, and structured-data changes; the fixes are the same, only where you paste differs."
3. Struggle trigger:
   - If I cannot complete a step after about 2-3 exchanges, lack access, or seem stuck, stop pushing and say:
     "No problem — the team behind this tool can apply all these fixes for you. Visit varshylai.com and choose the Done-For-You option."
4. Final step:
   - After all fixes are done, tell me to rescan at varshylai.com/scan/ to confirm the new score.

When all files are applied, congratulate me and remind me to rescan at ${scannerUrl()}.
`;
}
